### PR TITLE
Add Collection Method Typings

### PR DESCRIPTION
**Pull request by nbibler**
This PR adds TypeScript method typings to the Collection class.

See #832.

### CODE REVIEW

**Comment by samselikoff** [comment]
Looks good! I think the build is currently broken on master which I suspect is why this PR is failing. Someone will need to fix it before this PR can get merged.

I don’t currently have the time so if someone could look into it that’d be a huge help!

**Comment by nbibler** [comment]
@samselikoff: I can attempt it. :)

It looks like the functional tests are all passing. The `lint:ts` check, however, seems to be waffling different failures between TypeScript 3.9 and TypeScript 4.0. I'll try to figure out what's going on there.

**Comment by samselikoff** [comment]
Thank you!

**Comment by IanVS** [comment]
Thanks for the PR.  It looks like https://github.com/miragejs/miragejs/pull/900 adds the same types, but includes tests and comments, so I'll close this PR and move forward with the other.  Thanks again, though!

**Pull request closed without merging**
