### PR TITLE
Adding more descriptive namespace error

### PR DESCRIPTION
**Pull request by srikanthkyatham**

### CODE REVIEW

**Comment by IanVS** [comment]
>Fixing other lint error.

😂 

Sorry for the hassle.

**Comment by srikanthkyatham** [comment]
I am using prettier doing all the job :).

**Review by IanVS — APPROVED** [review]
Looks good to me, thanks!

**Comment by cah-briangantzler** [comment]
This code has been extracted to https://github.com/bgantzler/mirage-pretender/blob/master/lib/pretender-config.js#L309 and will be removed in my next PR. If there are any future updates to this file please make sure I know or do an equivalent PR for the mirage-pretender repo

Thanks

**Pull request merged**
