### PR TITLE
Updates typing for `Request.queryParams`

### PR DESCRIPTION
**Pull request by jasikpark**
This uses the type from https://github.com/tildeio/route-recognizer/blob/0a44fd86081ef425071839d3184e72fd2916d6fe/lib/route-recognizer.ts#L432 / https://github.com/tildeio/route-recognizer/blob/0a44fd86081ef425071839d3184e72fd2916d6fe/lib/route-recognizer.ts#L454

I think that https://github.com/tildeio/route-recognizer/blob/0a44fd86081ef425071839d3184e72fd2916d6fe/lib/route-recognizer.ts#L161 might contain the correct type for `params` a la #1026 but that seems to need better verification

### CODE REVIEW

**Comment by IanVS** [comment]
@jasikpark could you force-push to this branch to trigger a new run?  I'm curious if it will still fail, and I can't trigger a re-run (maybe it's too old)

**Comment by jasikpark** [comment]
@IanVS mind approving the CI run?

**Comment by IanVS** [comment]
@cah-brian-gantzler how will we handle types when we swap out MSW for pretender?  For instance, in this PR, we can see that the `queryParams` comes from pretender, which uses [`route-recognzier`](https://github.com/tildeio/route-recognizer), which has a type: https://github.com/tildeio/route-recognizer/blob/0a44fd86081ef425071839d3184e72fd2916d6fe/lib/route-recognizer.ts#L433

If one were to swap out MSW, would the types here change, I guess?

**Review by IanVS — APPROVED** [review]

**Comment by jasikpark** [comment]
thx for the approval! i don't have merge perms, so merge when you think it's ready to be

**Comment by cah-brian-gantzler** [comment]
@IanVS 
The query params are the params at the end of the url. The url is is the same wether its pretender or msw. I do not believe this would change at all.

**Comment by jasikpark** [comment]
so this can merge then?

**Comment by cah-brian-gantzler** [comment]
I am ok with this being merged

**Comment by jasikpark** [comment]
mind clicking the button for me then? I don't have the permissions for merging my own PR

**Comment by IanVS** [comment]
I will do it in a minute after giving one more quick look.

**Comment by IanVS** [comment]
>The url is is the same wether its pretender or msw. I do not believe this would change at all.

Yes, but the fake `Request` object that is given to the route callbacks comes from pretender today, and presumably from MSW if that gets swapped out.  Happy to run with this, but I think there may be nuances in the types if we allow changing out the mock layer.

**Pull request merged**
