### PR TITLE
wip canHandle

### PR DESCRIPTION
**Pull request by samselikoff**

### CODE REVIEW

**Comment by samselikoff** [comment]
Additional tests:

- dynamic segment
- resource helper
- wildcards *

**Comment by zeppelin** [comment]
@samselikoff this means that Mirage currently won't allow overriding handlers on an already established server?

**Comment by samselikoff** [comment]
@zeppelin nope this is for something different.

You can override handlers for sure, I do it all the time in tests, for example to test errors: https://miragejs.com/docs/testing/application-tests#testing-errors

**Comment by zeppelin** [comment]
@samselikoff hmm, currently trying to get it work, but I always get the original handler called. Something else must be off then in my setup...

**Comment by samselikoff** [comment]
Closing as this is outdated, but keeping reference in the Node tracking issue: https://github.com/miragejs/miragejs/issues/210

**Pull request closed without merging**
