### PR TITLE
Add a type for findBy with a predicate function

### LINKED ISSUE #665: Missing functional condition TS type in schema.findBy()

### PR DESCRIPTION
**Pull request by gentoid**
Fixes #665

### CODE REVIEW

**Comment by samselikoff** [comment]
Thank you! Looks like there's a TS test failure. (I don't know TS yet but just wanted to point this out.)

**Comment by gentoid** [comment]
yeah. Interestingly enough that locally this had passed. Going to investigate it.

**Comment by IanVS** [comment]
@gentoid we've fixed failing tests on master and updated our CI infrastructure.  Would you be willing to rebase this PR on latest master?

**Comment by gentoid** [comment]
@IanVS I'll check it

**Pull request merged**
